version: "3.9"
services:
  proxy:
    build: velocity
    ports:
      - "25565:25565"
    volumes:
      - H:\Network\Git\arematics_mc_plugins\Server\Proxy\plugins:/data/plugins
      - H:\Network\Git\arematics_mc_plugins\Server\Proxy\logs:/data/logs
    networks:
      - pvp_network
      - guns_network
      - lobby_network
      - default
  pvp:
    build: spigot
    ports:
      - "25566:25565"
    volumes:
      - H:\Network\Git\arematics_mc_plugins\Server\PvP\plugins:/data/plugins
      - H:\Network\Git\arematics_mc_plugins\Server\PvP\logs:/data/logs
    environment:
      XMX: 6G
      VIEW_DISTANCE: 8
    networks:
      - pvp_network
  guns:
    build: spigot
    ports:
      - "25567:25565"
    volumes:
      - H:\Network\Git\arematics_mc_plugins\Server\Guns\plugins:/data/plugins
      - H:\Network\Git\arematics_mc_plugins\Server\Guns\logs:/data/logs
    environment:
      XMX: 5G
      VIEW_DISTANCE: 10
    networks:
      - guns_network
  lobby-1:
    build: spigot
    ports:
      - "25568:25565"
    volumes:
      - H:\Network\Git\arematics_mc_plugins\Server\Lobby-01\plugins:/data/plugins
      - H:\Network\Git\arematics_mc_plugins\Server\Lobby-01\logs:/data/logs
    environment:
      XMX: 4G
      VIEW_DISTANCE: 12
    networks:
      - lobby_network
  lobby-2:
    build: spigot
    ports:
      - "25569:25565"
    volumes:
      - H:\Network\Git\arematics_mc_plugins\Server\Lobby-02\plugins:/data/plugins
      - H:\Network\Git\arematics_mc_plugins\Server\Lobby-02\logs:/data/logs
    environment:
      XMX: 4G
      VIEW_DISTANCE: 12
    networks:
      - lobby_network
  redis_pvp:
    image: redis
    networks:
      - pvp_network
  redis_guns:
    image: redis
    networks:
      - guns_network
  redis_lobby:
    image: redis
    networks:
      - lobby_network
  redis_global:
    image: redis
    networks:
      - pvp_network
      - guns_network
      - lobby_network
networks:
  pvp_network:
    driver: macvlan
  guns_network:
    driver: macvlan
  lobby_network:
    driver: macvlan
