name: McCore
author: Klysma
description: McCore by Arematics
version: 0.3.2
depend: [WorldEdit, WorldGuard]

main: com.arematics.minecraft.core.CoreBootstrap

commands:
  sound:
    description: Show valid sounds
    usage: /<command>
