name: McCore
author: Klysma
description: McCore by Arematics
version: 0.2.1
depend: [WorldEdit, WorldGuard]

main: com.arematics.minecraft.core.Bootstrap

commands:
  sound:
    description: Show valid sounds
    usage: /<command>
